INSERT INTO tokens(token,symbol) VALUES ('Bitcoin','XBT');
INSERT INTO tokens(token,symbol) VALUES ('Ethereum','ETH');
INSERT INTO tokens(token,symbol) VALUES ('Tether USD','USDT');
INSERT INTO tokens(token,symbol) VALUES ('Litecoin','LTC');
INSERT INTO tokens(token,symbol) VALUES ('Bitcoin Cash','BCH');
INSERT INTO tokens(token,symbol) VALUES ('Chainlink','LINK');
INSERT INTO tokens(token,symbol) VALUES ('Cardano','ADA');
INSERT INTO tokens(token,symbol) VALUES ('Polkadot','DOT');
INSERT INTO tokens(token,symbol) VALUES ('Lumen','XLM');
INSERT INTO tokens(token,symbol) VALUES ('EOS','EOS');
INSERT INTO tokens(token,symbol) VALUES ('Monero','XMR');
INSERT INTO tokens(token,symbol) VALUES ('TRON','TRX');
INSERT INTO tokens(token,symbol) VALUES ('Tezos','XTZ');