services:
  postgres-cte:
    image: postgres
    environment:
      POSTGRES_DB: cte
      POSTGRES_USER: cte
      POSTGRES_PASSWORD: password
    ports:
      - 5434:5432
  backend:
    image: crypto-tokens-backend
    ports:
      - 8080:8080
    environment:
      API_DB_URL: jdbc:postgresql://host.docker.internal:5434/cte
      API_DB_USERNAME: cte
      API_DB_PASSWORD: password
      API_LIQUIBASE_USERNAME: cte
      API_LIQUIBASE_PASSWORD: password
    depends_on:
      - postgres-cte
  frontend:
    image: crypto-tokens-frontend
    ports:
      - 4200:80